### ISSUE TITLE
Error BCP036 deploying CycleCloud Workspace for Slurm environment using the CLI

### ISSUE THREAD

**Issue by Al77056** [Azure/cyclecloud-slurm-workspace#136]
## Version
2024.11.08

## In what area(s)?
Using az cli for deployment

## Actual Behavior
Received two errors after two warnings and nothing was created.
/home/alu/cyclecloud-slurm-workspace/bicep/ccw.bicep(103,30) : Warning BCP318: The value of type "null | { id: string, name: string, rg: string }" may be null at the start of the deployment, which would cause this access expression (and the overall deployment with it) to fail. [https://aka.ms/bicep/core-diagnostics#BCP318]
/home/alu/cyclecloud-slurm-workspace/bicep/ccw.bicep(193,31) : Warning BCP318: The value of type "null | { id: string, name: string, rg: string }" may be null at the start of the deployment, which would cause this access expression (and the overall deployment with it) to fail. [https://aka.ms/bicep/core-diagnostics#BCP318]
/home/alu/cyclecloud-slurm-workspace/bicep/ccw.bicep(99,10) : Error BCP036: The property "scope" expected a value of type "resourceGroup" but the provided value is of type "{ id: string, location: string, managedBy: string, name: string, properties: properties, tags: Tags, type: string }". [https://aka.ms/bicep/core-diagnostics#BCP036]
/home/alu/cyclecloud-slurm-workspace/bicep/mainTemplate.bicep(43,25) : Error BCP104: The referenced module has errors. [https://aka.ms/bicep/core-diagnostics#BCP104]

## Steps to Reproduce the Problem
Following the steps described at https://learn.microsoft.com/en-us/azure/cyclecloud/how-to/ccws/deploy-with-cli?view=cyclecloud-8, I have created a parameters file named cyclecloud-zlu.json. 

After running the command to accept the image plan, I ran "az deployment sub create --template-file ./bicep/mainTemplate.bicep --parameters /mnt/c/tmp/slurm-cyclecloud-template.json --location southcentralus --name cc-zlu", and received the above warnings and errors.

**Comment by xpillons** [comment]
@Al77056  Thank you for reporting your error, would you mind sharing your parameter file after having sanitized it by cleaning the subscriptions values and private information ?

**Comment by Al77056** [comment]
It is indeed an issue of bicep version 0.31.34. After downgrading to 0.30.23 it is deploying.
