### ISSUE TITLE
creating cyclecloud using az cli failed with error RoleAssignmentUpdateNotPermitted

### ISSUE THREAD

**Issue by Al77056** [Azure/cyclecloud-slurm-workspace#139]
## Version
2024.11.08

## In what area(s)?
Role assignment during the creation of the ccw

## Expected Behavior
All deployments succeed.

## Actual Behavior
Even though I am an owner of the subscription, I received error indicating the role assignments failed.

The deployment named "ccwRoleFor-ccw-cyclecloud-southcentralus" failed with the following message:
{
  "code": "RoleAssignmentUpdateNotPermitted",
  "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
}

## Steps to Reproduce the Problem

The deployment template for the role assignment is included below:

{
    "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "type": "String"
        },
        "rgID": {
            "type": "String"
        },
        "roles": {
            "type": "Array"
        },
        "principalId": {
            "type": "String"
        }
    },
    "variables": {
        "role_lookup": {
            "Contributor": "[resourceId('microsoft.authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')]",
            "UserAccessAdministrator": "[resourceId('microsoft.authorization/roleDefinitions', '18d7d88d-d35e-4fb5-a5c3-7773c20a72d9')]",
            "Storage Account Contributor": "[resourceId('microsoft.authorization/roleDefinitions', '17d1049b-9a84-46fb-8f53-869881c3d3ab')]",
            "Storage Blob Data Contributor": "[resourceId('microsoft.authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')]"
        }
    },
    "resources": [
        {
            "type": "Microsoft.Authorization/roleAssignments",
            "apiVersion": "2022-04-01",
            "name": "[guid(parameters('name'), parameters('roles')[copyIndex()], parameters('rgID'), subscription().id)]",
            "properties": {
                "roleDefinitionId": "[variables('role_lookup')[parameters('roles')[copyIndex()]]]",
                "principalId": "[parameters('principalId')]",
                "principalType": "ServicePrincipal"
            },
            "copy": {
                "name": "roleAssignments",
                "count": "[length(parameters('roles'))]"
            }
        }
    ]
}

It ran with the following parameters:
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "name": {
            "value": "ccw-cyclecloud"
        },
        "rgID": {
            "value": "/subscriptions/6700a606-14eb-45ea-b304-ad5d12eccef9/resourceGroups/zlu-test"
        },
        "roles": {
            "value": [
                "Contributor",
                "Storage Account Contributor",
                "Storage Blob Data Contributor"
            ]
        },
        "principalId": {
            "value": "6ebb0e87-24b3-4923-a9d2-eff21106ee10"
        }
    }
}

I tried to assign principalId "6ebb0e87-24b3-4923-a9d2-eff21106ee10", which corresponds to the ccw-cyclecloud-vm, with role "Storage Account Contributor" using az cli after the deployment failed and the assignment completed successfully.

az role assignment create --assignee-object-id 6ebb0e87-24b3-4923-a9d2-eff21106ee10 --role "Storage Account Contributor" --scope $rg_resource_id
RBAC service might reject creating role assignment without --assignee-principal-type in the future. Better to specify --assignee-principal-type manually.
{
  "condition": null,
  "conditionVersion": null,
  "createdBy": null,
  "createdOn": "2024-11-16T04:43:59.526897+00:00",
  "delegatedManagedIdentityResourceId": null,
  "description": null,
  "id": "/subscriptions/6700a606-14eb-45ea-b304-ad5d12eccef9/resourceGroups/zlu-test/providers/Microsoft.Authorization/roleAssignments/d1d24f00-ca4d-45bf-a2ff-28a376d5a4cc",
  "name": "d1d24f00-ca4d-45bf-a2ff-28a376d5a4cc",
  "principalId": "6ebb0e87-24b3-4923-a9d2-eff21106ee10",
  "principalType": "ServicePrincipal",
  "resourceGroup": "zlu-test",
  "roleDefinitionId": "/subscriptions/6700a606-14eb-45ea-b304-ad5d12eccef9/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab",
  "scope": "/subscriptions/6700a606-14eb-45ea-b304-ad5d12eccef9/resourceGroups/zlu-test",
  "type": "Microsoft.Authorization/roleAssignments",
  "updatedBy": "1f93f3ab-a93c-417d-a9e0-c2a6743f2682",
  "updatedOn": "2024-11-16T04:44:00.935654+00:00"
}

**Comment by xpillons** [comment]
This happen when you deploy multiple times in the same RG because role assignments are not automatically cleaned. Please follow these instructions to cleanup them https://learn.microsoft.com/en-us/azure/cyclecloud/how-to/ccws/cleanup-roles?view=cyclecloud-8 or deploy in a different RG.

**Comment by Al77056** [comment]
Indeed I was deploying in the same RG. It's so weird that deleting the RG does not delete everything associated with it. I ran the delete_roles.sh script and it fixed the issue. It's weirder that it's necessary to create the RG before the role assignments can be deleted, but it gets the job done.

BTW, the current version of delete_roles.sh does not support the "--location" parameter.
