### ISSUE TITLE
Default GPU VM size is not set

### ISSUE THREAD

**Issue by ossonts** [Azure/cyclecloud-slurm-workspace#53]
On the default UI template: tag/2024.06.06

Line: https://github.com/Azure/cyclecloud-slurm-workspace/blob/4e29c9fbca0dba12ed21169a3362eb1f3c54506e/uidefinitions/createUiDefinition.json#L1208

List is set to include only :
Standard_ND96asr_v4

This appears as empty depending on regions

![image](https://github.com/Azure/cyclecloud-slurm-workspace/assets/472243/84dd0ea9-4f42-41d7-84cf-ae494ba01349)

Change:
Add others ; eg NC24?

**Comment by xpillons** [comment]
Thanks @ossonts, it's probably because of a lack of quota in the region. Which region were you targeting ?

**Comment by xpillons** [comment]
this is closed by #56
